// Table definitions
export { provinces } from './provinces'
export { regions } from './regions'
export { originCities } from './origin-cities'
export { interests } from './interests'
export { travelTypes } from './travel-types'
export { placeTypes } from './place-types'
export { places } from './places'
export { placeImages } from './place-images'
export { placeContacts } from './place-contacts'
export { placeInterests } from './place-interests'
export { placeBestMonths } from './place-best-months'
export { ratings } from './ratings'
export { newsletterSubscribers } from './newsletter'

// Relations
export { provincesRelations } from './provinces'
export { regionsRelations } from './regions'
export { originCitiesRelations } from './origin-cities'
export { interestsRelations } from './interests'
export { travelTypesRelations } from './travel-types'
export { placeTypesRelations } from './place-types'
export { placesRelations } from './places'
export { placeImagesRelations } from './place-images'
export { placeContactsRelations } from './place-contacts'
export { placeInterestsRelations } from './place-interests'
export { placeBestMonthsRelations } from './place-best-months'
export { ratingsRelations } from './ratings'
export { newsletterSubscribersRelations } from './newsletter'

// Types
export type { Province, NewProvince } from './provinces'
export type { Region, NewRegion } from './regions'
export type { OriginCity, NewOriginCity } from './origin-cities'
export type { Interest, NewInterest } from './interests'
export type { TravelType, NewTravelType } from './travel-types'
export type { PlaceType, NewPlaceType } from './place-types'
export type { Place, NewPlace } from './places'
export type { PlaceImage, NewPlaceImage } from './place-images'
export type { PlaceContact, NewPlaceContact } from './place-contacts'
export type { PlaceInterest, NewPlaceInterest } from './place-interests'
export type { PlaceBestMonth, NewPlaceBestMonth } from './place-best-months'
export type { Rating, NewRating } from './ratings'
export type { NewsletterSubscriber, NewNewsletterSubscriber } from './newsletter'
